/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Public } from "../../decorators/public.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePreRegisterArgs } from "./CreatePreRegisterArgs";
import { UpdatePreRegisterArgs } from "./UpdatePreRegisterArgs";
import { DeletePreRegisterArgs } from "./DeletePreRegisterArgs";
import { PreRegisterFindManyArgs } from "./PreRegisterFindManyArgs";
import { PreRegisterFindUniqueArgs } from "./PreRegisterFindUniqueArgs";
import { PreRegister } from "./PreRegister";
import { PreRegisterService } from "../preRegister.service";

@graphql.Resolver(() => PreRegister)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PreRegisterResolverBase {
  constructor(
    protected readonly service: PreRegisterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PreRegister",
    action: "read",
    possession: "any",
  })
  async _preRegistersMeta(
    @graphql.Args() args: PreRegisterFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PreRegister])
  @nestAccessControl.UseRoles({
    resource: "PreRegister",
    action: "read",
    possession: "any",
  })
  async preRegisters(
    @graphql.Args() args: PreRegisterFindManyArgs
  ): Promise<PreRegister[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PreRegister, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PreRegister",
    action: "read",
    possession: "own",
  })
  async preRegister(
    @graphql.Args() args: PreRegisterFindUniqueArgs
  ): Promise<PreRegister | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.Mutation(() => PreRegister)
  async createPreRegister(
    @graphql.Args() args: CreatePreRegisterArgs
  ): Promise<PreRegister> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PreRegister)
  @nestAccessControl.UseRoles({
    resource: "PreRegister",
    action: "update",
    possession: "any",
  })
  async updatePreRegister(
    @graphql.Args() args: UpdatePreRegisterArgs
  ): Promise<PreRegister | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PreRegister)
  @nestAccessControl.UseRoles({
    resource: "PreRegister",
    action: "delete",
    possession: "any",
  })
  async deletePreRegister(
    @graphql.Args() args: DeletePreRegisterArgs
  ): Promise<PreRegister | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
