/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ScheduleConfigUpdateManyWithoutUsersInput } from "./ScheduleConfigUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { UsuarioTemaUpdateManyWithoutUsersInput } from "./UsuarioTemaUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatar?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: () => ScheduleConfigUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleConfigUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ScheduleConfigUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  scheduleConfigs?: ScheduleConfigUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => UsuarioTemaUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsuarioTemaUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsuarioTemaUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  usuarioTemas?: UsuarioTemaUpdateManyWithoutUsersInput;
}
export { UserUpdateInput };
