/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ScheduleConfigCreateNestedManyWithoutUsersInput } from "./ScheduleConfigCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { UsuarioTemaCreateNestedManyWithoutUsersInput } from "./UsuarioTemaCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatar?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => ScheduleConfigCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleConfigCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ScheduleConfigCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  scheduleConfigs?: ScheduleConfigCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UsuarioTemaCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsuarioTemaCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsuarioTemaCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  usuarioTemas?: UsuarioTemaCreateNestedManyWithoutUsersInput;
}
export { UserCreateInput };
